services:
  mariadb:
    image: "mariadb"
    restart: "on-failure:3"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "products"

  backend:
    build: "./backend"
    depends_on:
      - "mariadb"
    restart: "on-failure:3"
    environment:
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "${DB_ROOT_PASSWORD}"
      SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb:3306/products"
    ports:
      - "${BACKEND_EXTERNAL_PORT}:8080"

  phpmyadmin:
    image: "phpmyadmin"
    depends_on:
      - "mariadb"
    restart: "on-failure:3"
    environment:
      PMA_HOST: "mariadb"
    ports:
      - "127.0.0.1:${PHPMYADMIN_EXTERNAL_PORT}:80"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - "backend"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
