application:
  security:
    jwt:
      secret-key: "QUJDREVGR0hJSktMTU9QUVJTVFVWV1hZWjAxMjM0NTY3ODlBQkNERUZHSElKS0xNT1BRUlNUVVZXWFlaMDEyMzQ1Njc4OUFCQ0RFRkdISUpLTE1PUFFSU1RVVldYWVowMTIzNDU2Nzg5"
      expiration: 86400000
      refresh-token:
        expiration: 604800000
